[gateway]
gateway-lxc ansible_host=gateway.homelab.lan ansible_user=root ansible_ssh_private_key_file=~/.ssh/homelab-gateway ansible_python_interpreter=/usr/bin/python3

[application]
app-vm ansible_host=application.homelab.lan ansible_user=rioly ansible_ssh_private_key_file=~/.ssh/homelab-application ansible_python_interpreter=/usr/bin/python3
