global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: true # exposed only in docker internal network

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      aliasHeadersStrategy: reject

  websecure:
    address: ":443"
    http:
      aliasHeadersStrategy: reject
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/24"   # internal VM subnet
        - "172.16.0.0/12" # docker internal net

certificatesResolvers:
  duckdns-resolver:
    acme:
      email: "rioly@proton.me"
      storage: "/acme.json"
      dnsChallenge:
        provider: duckdns
        propagation:
          delayBeforeChecks: 60

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy-net"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-299"
      - "400-599"
