global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
      aliasHeadersStrategy: reject

  websecure:
    address: ":443"
    http:
      aliasHeadersStrategy: reject

certificatesResolvers:
  duckdns-resolver:
    acme:
      email: "rioly@proton.me"
      storage: "/acme.json"
      dnsChallenge:
        provider: duckdns
        propagation:
          delayBeforeChecks: 60

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy-net"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
