- name: Configure Ubuntu-Server Application
  hosts: application
  become: true

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: true

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add rioly user to docker group
      ansible.builtin.user:
        name: rioly
        groups: docker
        append: true
