- name: Configure Ubuntu-Server Application
  hosts: application
  become: true

  tasks:
    - name: Set up Docker prerequisite engine and networks
      ansible.builtin.import_tasks: tasks/01-docker-setup.yml

    - name: Create main apps directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: rioly
        group: rioly
        mode: '0755'
      loop:
        - /home/rioly/apps
        - /home/rioly/apps/dynamic
        - /home/rioly/apps/authelia
        - /home/rioly/apps/postgres/data
        - /home/rioly/apps/postgres/init

    - name: Set up Traefik proxy files
      ansible.builtin.import_tasks: tasks/02-traefik-setup.yml

    - name: Template Postgres init
      ansible.builtin.template:
        src: ../docker/postgres/init/{{ item }}.j2
        dest: /home/rioly/apps/postgres/init/{{ item }}
        owner: rioly
        group: rioly
        mode: '0644'
      loop:
        - 01-authelia.sql
        - 02-vaultwarden.sql

    - name: Set up Authelia prerequisite
      ansible.builtin.import_tasks: tasks/03-authelia-setup.yml

    - name: Deploy homelab
      ansible.builtin.import_tasks: tasks/deploy.yml

    - name: Configure backup
      ansible.builtin.import_tasks: tasks/backup-setup.yml
