title: Home Lab
description: Rioly Homelab Dashboard
theme: dark
color: slate
background:
  image: https://istockphoto.com/photos/ascii-photos
  blur: md
  opacity: 50

headerStyle: clean
layout:
  Services:
    style: grid
    columns: 3

showStats: true
statusStyle: dot
