http:
  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?type=plain"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
